# test_microbin_report_html_link.ps1 - focused regression test for stamping a
# successful MicroBin paste URL into the generated HTML report.
# Runs locally with a disposable receiver only; no network, no live uploads.
# Covers the success path (LF and CRLF reports), HTML escaping of a
# query-bearing paste URL, upload failure leaving the report untouched,
# hostile Location headers never reaching the HTML, the </body>-only
# fallback, the no-marker loud failure, and the missing-report wiring error.
# PowerShell 5.1 compatible. Pure ASCII, no BOM.
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$uploaderPath = Join-Path $repoRoot 'Submit-ConnectWiseReport.ps1'
$uploaderSource = [System.IO.File]::ReadAllText($uploaderPath)
$startSource = [System.IO.File]::ReadAllText((Join-Path $repoRoot 'START-HERE.bat'))
$cleanupSource = [System.IO.File]::ReadAllText((Join-Path $repoRoot 'sc-cleanup.ps1'))
$probeRoot = Join-Path ([System.IO.Path]::GetTempPath()) ('scc-microbin-html-link-' + [guid]::NewGuid().ToString('N'))
$null = New-Item -ItemType Directory -Path $probeRoot -Force
$scenarioProcesses = @()

$failures = @()
function Check {
    param([string]$Name, [bool]$Condition, [string]$Details)
    if ($Condition) {
        Write-Host ("PASS  " + $Name)
    } else {
        $message = "FAIL  " + $Name
        if ($Details) { $message += " - " + $Details }
        Write-Host $message
        $script:failures += $message
    }
}

# ---- Source-level contract checks ------------------------------------------
Check 'uploader declares the -ReportHtml parameter' $uploaderSource.Contains('$ReportHtml') $uploaderSource
Check 'uploader HTML-escapes the URL before writing it' $uploaderSource.Contains("Replace('&', '&amp;')") $uploaderSource
Check 'uploader has the paste-link annotator' $uploaderSource.Contains('Add-ReportPasteLink') $uploaderSource
Check 'annotator is only reachable after a successful upload' ($uploaderSource.LastIndexOf('Add-ReportPasteLink -ReportHtml') -gt $uploaderSource.IndexOf('MICROBIN UPLOAD: ')) $uploaderSource
Check 'guided launcher passes the report path to the uploader' $startSource.Contains('-ReportHtml') $startSource
Check 'cleanup runner passes the report path to the uploader' $cleanupSource.Contains('-ReportHtml') $cleanupSource

$psHost = $null
if ($PSVersionTable.PSEdition -eq 'Desktop') {
    $psHost = Join-Path $PSHOME 'powershell.exe'
} else {
    $psHost = (Get-Command pwsh -ErrorAction Stop).Source
}

$workDir = Join-Path $probeRoot 'run'
$null = New-Item -ItemType Directory -Path $workDir -Force
$findingsPath = Join-Path $workDir 'findings.json'

$fixture = [ordered]@{
    SchemaVersion = 4
    GeneratedUtc = '2026-09-06T10:00:00Z'
    ComputerName = 'CLIENT-99'
    RunAsUser = 'Bob'
    DeliveryContext = 'malvertising'
    Instances = @(
        [ordered]@{
            Identifier = 'ABCDEF123456'
            RelayHost = 'evil-relay.example'
            RelayPort = 443
            InstallDir = 'C:\Users\Bob\AppData\Local\ScreenConnect Client'
            ParamBlob = 'do-not-upload-this-secret'
            Files = @(
                [ordered]@{
                    Path = 'C:\Users\Bob\Downloads\dropper.ps1'
                    SHA256 = 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'
                    SignatureStatus = 'NotSigned'
                }
            )
        }
    )
}
$fixture | ConvertTo-Json -Depth 12 | Set-Content -LiteralPath $findingsPath -Encoding ASCII

# ---- Minimal generated-report fixtures -------------------------------------
# The real New-InvestigationReport.ps1 always emits <footer> ... </footer>
# then </body></html>; the fixtures mirror that shape plus the edge variants.
function Write-HtmlFixture {
    param([string]$Path, [string[]]$BodyLines, [bool]$Crlf)
    $separator = if ($Crlf) { "`r`n" } else { "`n" }
    $text = ($BodyLines -join $separator) + $separator
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $text, $utf8NoBom)
}

$reportLf = Join-Path $workDir 'report-lf.html'
Write-HtmlFixture -Path $reportLf -Crlf $false -BodyLines @(
    '<!DOCTYPE html>'
    '<html lang="en">'
    '<head><meta charset="utf-8"><title>Investigation report</title></head>'
    '<body>'
    '<main><p>SC-MARKER-KEEP-7f3a</p></main>'
    '<footer>'
    '  Generated by fixture.'
    '</footer>'
    '</body>'
    '</html>'
)

$reportCrlf = Join-Path $workDir 'report-crlf.html'
Write-HtmlFixture -Path $reportCrlf -Crlf $true -BodyLines @(
    '<!DOCTYPE html>'
    '<html lang="en">'
    '<head><meta charset="utf-8"><title>Investigation report</title></head>'
    '<body>'
    '<main><p>SC-MARKER-KEEP-7f3a</p></main>'
    '<footer>'
    '  Generated by fixture.'
    '</footer>'
    '</body>'
    '</html>'
)

$reportBodyOnly = Join-Path $workDir 'report-body-only.html'
Write-HtmlFixture -Path $reportBodyOnly -Crlf $false -BodyLines @(
    '<!DOCTYPE html>'
    '<html><body>'
    '<p>SC-MARKER-BODY-ONLY-19c2</p>'
    '</body></html>'
)

$reportNoMarker = Join-Path $workDir 'report-no-marker.html'
Write-HtmlFixture -Path $reportNoMarker -Crlf $false -BodyLines @(
    '<!DOCTYPE html>'
    '<html><body><p>no closing markers here</p>'
)

$reportMissing = Join-Path $workDir 'does-not-exist.html'

# ---- Disposable MicroBin receiver ------------------------------------------
$receiverScript = Join-Path $probeRoot 'microbin_receiver.py'
@'
import json
import re
import sys
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

port_path = Path(sys.argv[1])
log_path = Path(sys.argv[2])
mode = sys.argv[3]

class Receiver(BaseHTTPRequestHandler):
    seq = 0

    def do_POST(self):
        Receiver.seq += 1
        n = Receiver.seq
        length = int(self.headers.get('Content-Length', '-1'))
        body = self.rfile.read(length) if length > 0 else b''
        content_type = self.headers.get('Content-Type', '')
        fields = {}
        match = re.search(r'boundary=([^;]+)', content_type)
        if match:
            boundary = match.group(1).encode('utf-8')
            for part in body.split(b'--' + boundary):
                part = part.strip(b'\r\n')
                if not part or part == b'--' or b'\r\n\r\n' not in part:
                    continue
                head, value = part.split(b'\r\n\r\n', 1)
                if value.endswith(b'\r\n'):
                    value = value[:-2]
                name_match = re.search(r'name="([^"]+)"', head.decode('latin-1'))
                if name_match:
                    fields[name_match.group(1)] = value.decode('utf-8', 'replace')
        if mode == 'always503':
            status, location, response = 503, None, b'server error'
        elif mode == 'hostile':
            status, location, response = 302, '/upload/"><script>alert(1)</script>', b''
        elif mode == 'queryurl':
            base = 'http://127.0.0.1:%d' % self.server.server_port
            status, location, response = 302, base + '/upload/pig-dog-cat?aa=1&bb=two', b''
        else:
            status, location, response = 302, '/upload/pig-dog-cat', b''
        entry = {
            'n': n,
            'path': self.path,
            'content_type': content_type,
            'fields': fields,
            'status_sent': status,
            'location': location,
        }
        with log_path.open('a', encoding='utf-8') as log:
            log.write(json.dumps(entry) + '\n')
        self.send_response(status)
        if location:
            self.send_header('Location', location)
        self.send_header('Content-Length', str(len(response)))
        self.end_headers()
        if response:
            self.wfile.write(response)

    def log_message(self, format, *args):
        pass

server = HTTPServer(('127.0.0.1', 0), Receiver)
port_path.write_text(str(server.server_port), encoding='ascii')
server.serve_forever()
'@ | Set-Content -LiteralPath $receiverScript -Encoding ASCII

$pythonCommand = Get-Command python3 -ErrorAction SilentlyContinue
if (-not $pythonCommand) { $pythonCommand = Get-Command python -ErrorAction SilentlyContinue }
if (-not $pythonCommand) { throw 'python is required for the disposable MicroBin receiver test' }
$pythonPath = if ($pythonCommand.Source) { $pythonCommand.Source } else { $pythonCommand.Path }

function Start-MicroBinServer {
    param([string]$Mode)
    $suffix = [guid]::NewGuid().ToString('N')
    $portFile = Join-Path $probeRoot ('receiver-' + $Mode + '-' + $suffix + '.port')
    $logFile = Join-Path $probeRoot ('receiver-' + $Mode + '-' + $suffix + '.log')
    $stdOut = Join-Path $probeRoot ('receiver-' + $Mode + '-' + $suffix + '.stdout')
    $stdErr = Join-Path $probeRoot ('receiver-' + $Mode + '-' + $suffix + '.stderr')
    $serverArgs = @($receiverScript, $portFile, $logFile, $Mode)
    $proc = Start-Process -FilePath $pythonPath -ArgumentList $serverArgs -PassThru `
        -RedirectStandardOutput $stdOut -RedirectStandardError $stdErr
    $script:scenarioProcesses += $proc
    $port = $null
    for ($i = 0; $i -lt 50; $i++) {
        if (Test-Path -LiteralPath $portFile) {
            try { $port = [int](Get-Content -LiteralPath $portFile -Raw); break } catch { }
        }
        Start-Sleep -Milliseconds 100
    }
    if ($null -eq $port) { throw 'MicroBin receiver did not start' }
    return @{ Port = $port; Log = $logFile; ProcessId = $proc.Id; StdOut = $stdOut; StdErr = $stdErr }
}

function Invoke-UploaderRun {
    param([object[]]$ExtraArgs)
    $callArgs = @('-NoLogo', '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $uploaderPath) + $ExtraArgs
    $runOutput = & $psHost @callArgs 2>&1
    return @{ Output = ($runOutput -join "`n"); Rc = $LASTEXITCODE }
}

function Read-ReportText {
    param([string]$Path)
    return [System.IO.File]::ReadAllText($Path)
}

function Test-ReportAsciiNoBom {
    param([string]$Path)
    $bytes = [System.IO.File]::ReadAllBytes($Path)
    $hasBom = $bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF
    $nonAscii = @($bytes | Where-Object { $_ -gt 127 }).Count -gt 0
    return (-not $hasBom) -and (-not $nonAscii)
}

function Test-ReportHasExactlyOnePasteLink {
    param([string]$Text)
    $comment = '<!-- ScreenConnect Cleanup: sanitized MicroBin paste of this report'
    $anchorCount = ([regex]::Matches($Text, '<a href=')).Count
    return $Text.Contains($comment) -and $Text.Contains('Sanitized paste (MicroBin)') -and $anchorCount -eq 1
}

try {
    # ---- 1. Successful upload appends the paste link (LF report) ------------
    $srv1 = Start-MicroBinServer -Mode 'success'
    $url1 = 'http://127.0.0.1:' + $srv1.Port
    $before1 = Read-ReportText $reportLf
    $out1 = Invoke-UploaderRun @('-FindingsJson', $findingsPath, '-WorkDir', $workDir, '-MicroBinUrl', $url1, '-ReportHtml', $reportLf, '-AllowInsecureRelay')
    $text1 = $out1.Output
    Check 'successful upload annotates the report and exits 0' ($out1.Rc -eq 0 -and $text1 -match 'MICROBIN UPLOAD: ' -and $text1 -match 'MICROBIN PASTE LINK: added to') $text1
    $html1 = Read-ReportText $reportLf
    Check 'paste link names the paste URL' ($html1.Contains('href="' + $url1 + '/upload/pig-dog-cat"')) $html1
    Check 'exactly one link block was inserted' (Test-ReportHasExactlyOnePasteLink $html1) $html1
    Check 'original report content is preserved' ($html1.Contains('SC-MARKER-KEEP-7f3a') -and $html1.EndsWith('</html>' + "`n") -or $html1.EndsWith('</html>')) $html1
    Check 'link block uses the report LF newline style' ($html1.Contains("`n<!-- ScreenConnect Cleanup") -and -not $html1.Contains("`r`n<!-- ScreenConnect Cleanup")) $html1
    Check 'rewritten report stays ASCII with no BOM' (Test-ReportAsciiNoBom $reportLf) $html1

    # ---- 2. Query-bearing paste URL is HTML-escaped (CRLF report) -----------
    $srv2 = Start-MicroBinServer -Mode 'queryurl'
    $url2 = 'http://127.0.0.1:' + $srv2.Port
    $out2 = Invoke-UploaderRun @('-FindingsJson', $findingsPath, '-WorkDir', $workDir, '-MicroBinUrl', $url2, '-ReportHtml', $reportCrlf, '-AllowInsecureRelay')
    $text2 = $out2.Output
    Check 'query-bearing URL upload succeeds' ($out2.Rc -eq 0 -and $text2 -match 'MICROBIN UPLOAD: ') $text2
    $html2 = Read-ReportText $reportCrlf
    Check 'ampersand in the paste URL is HTML-escaped' ($html2.Contains('href="' + $url2 + '/upload/pig-dog-cat?aa=1&amp;bb=two"')) $html2
    Check 'raw ampersand never appears in the href' (-not $html2.Contains('?aa=1&bb=')) $html2
    Check 'link block uses the report CRLF newline style' ($html2.Contains("`r`n<!-- ScreenConnect Cleanup")) $html2
    Check 'CRLF report stays ASCII with no BOM' (Test-ReportAsciiNoBom $reportCrlf) $html2

    # ---- 3. Upload failure never touches the report --------------------------
    $srv3 = Start-MicroBinServer -Mode 'always503'
    $url3 = 'http://127.0.0.1:' + $srv3.Port
    $before3 = Read-ReportText $reportLf
    $out3 = Invoke-UploaderRun @('-FindingsJson', $findingsPath, '-WorkDir', $workDir, '-MicroBinUrl', $url3, '-ReportHtml', $reportLf, '-AllowInsecureRelay')
    $text3 = $out3.Output
    Check 'server failure fails the run loudly' ($out3.Rc -ne 0 -and $text3 -match 'MICROBIN UPLOAD FAILED: ') $text3
    Check 'failure output never claims a paste link was added' ($text3 -notmatch 'MICROBIN PASTE LINK: added') $text3
    Check 'report file is byte-identical after a failed upload' ((Read-ReportText $reportLf) -eq $before3) $text3

    # ---- 4. Hostile Location header is rejected before it reaches the HTML --
    $srv4 = Start-MicroBinServer -Mode 'hostile'
    $url4 = 'http://127.0.0.1:' + $srv4.Port
    $before4 = Read-ReportText $reportCrlf
    $out4 = Invoke-UploaderRun @('-FindingsJson', $findingsPath, '-WorkDir', $workDir, '-MicroBinUrl', $url4, '-ReportHtml', $reportCrlf, '-AllowInsecureRelay')
    $text4 = $out4.Output
    Check 'markup-shaped Location is rejected as not a paste URL' ($out4.Rc -ne 0 -and $text4 -match 'does not look like a paste URL') $text4
    Check 'rejected Location never annotates the report' ((Read-ReportText $reportCrlf) -eq $before4) $text4

    # ---- 5. No -ReportHtml leaves the uploader a silent no-op ----------------
    $srv5 = Start-MicroBinServer -Mode 'success'
    $url5 = 'http://127.0.0.1:' + $srv5.Port
    $out5 = Invoke-UploaderRun @('-FindingsJson', $findingsPath, '-WorkDir', $workDir, '-MicroBinUrl', $url5, '-AllowInsecureRelay')
    Check 'upload without a report path still succeeds' ($out5.Rc -eq 0 -and $out5.Output -match 'MICROBIN UPLOAD: ') $out5.Output
    Check 'no paste-link step runs without -ReportHtml' ($out5.Output -notmatch 'MICROBIN PASTE LINK') $out5.Output

    # ---- 6. Missing report path fails loudly (wiring error) ------------------
    $srv6 = Start-MicroBinServer -Mode 'success'
    $url6 = 'http://127.0.0.1:' + $srv6.Port
    $out6 = Invoke-UploaderRun @('-FindingsJson', $findingsPath, '-WorkDir', $workDir, '-MicroBinUrl', $url6, '-ReportHtml', $reportMissing, '-AllowInsecureRelay')
    $text6 = $out6.Output
    Check 'upload succeeds but the missing report is a loud failure' ($out6.Rc -ne 0 -and $text6 -match 'MICROBIN UPLOAD: ' -and $text6 -match 'MICROBIN PASTE LINK FAILED: report HTML was not found') $text6

    # ---- 7. </body>-only report: link lands before </body> -------------------
    $srv7 = Start-MicroBinServer -Mode 'success'
    $url7 = 'http://127.0.0.1:' + $srv7.Port
    $out7 = Invoke-UploaderRun @('-FindingsJson', $findingsPath, '-WorkDir', $workDir, '-MicroBinUrl', $url7, '-ReportHtml', $reportBodyOnly, '-AllowInsecureRelay')
    $text7 = $out7.Output
    Check 'body-only report is annotated and exits 0' ($out7.Rc -eq 0 -and $text7 -match 'MICROBIN PASTE LINK: added to') $text7
    $html7 = Read-ReportText $reportBodyOnly
    Check 'link is inserted before </body> and the tail is intact' ($html7.Contains('SC-MARKER-BODY-ONLY-19c2') -and $html7.IndexOf('<a href=') -gt 0 -and $html7.IndexOf('<a href=') -lt $html7.IndexOf('</body>') -and $html7.EndsWith('</body></html>' + "`n")) $html7

    # ---- 8. Report with no closing marker fails loudly, file untouched -------
    $srv8 = Start-MicroBinServer -Mode 'success'
    $url8 = 'http://127.0.0.1:' + $srv8.Port
    $before8 = Read-ReportText $reportNoMarker
    $out8 = Invoke-UploaderRun @('-FindingsJson', $findingsPath, '-WorkDir', $workDir, '-MicroBinUrl', $url8, '-ReportHtml', $reportNoMarker, '-AllowInsecureRelay')
    $text8 = $out8.Output
    Check 'marker-less report fails loudly' ($out8.Rc -ne 0 -and $text8 -match 'MICROBIN PASTE LINK FAILED: report HTML has no closing </body> marker') $text8
    Check 'marker-less report is left untouched' ((Read-ReportText $reportNoMarker) -eq $before8) $text8
} finally {
    foreach ($proc in $scenarioProcesses) {
        if ($proc -and -not $proc.HasExited) {
            Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue
        }
    }
    Remove-Item -LiteralPath $probeRoot -Recurse -Force -ErrorAction SilentlyContinue
}

if ($failures.Count -gt 0) {
    Write-Host ("$($failures.Count) MicroBin report HTML link test(s) failed")
    exit 1
}
Write-Host 'ALL MICROBIN REPORT HTML LINK TESTS PASSED'
exit 0
